#
# Este archivo contiene indicadores de configuración para personalizar su sitio
#

# Nombre de su sitio (mostrado en el encabezado)
name: Blog AMORA

# Nombre de su sitio (mostrado en el encabezado)
description: Blog dedicado a las mujeres que aman a otras mujeres.

# URL de su avatar o foto de perfil (puede usar su foto de perfil de GitHub)
avatar: https://github.com/AviReyes/AviReyes.github.io/blob/master/images/amoras.jpg?raw=true

#
# Estos son opcionales
#

# Incluye un icono en el pie de página para cada nombre de usuario que ingrese
footer-links:
  dribbble:
  email: avitareyes@gmail.com
  facebook:
  
  flickr:
  github: https://AviReyes.github.io
  instagram:
  linkedin:
  pinterest:
  rss: # simplemente escriba cualquier cosa aquí para ver un icono de RSS que funcione
  twitter: 
  stackoverflow: # su perfil de stackoverflow, p. ej. "usuarios / 50476 / bart-kiers"
  youtube: # channel / <your_long_string> o usuario / <user-name>
  googleplus: # cualquier cosa en su nombre de usuario de perfil que venga después de plus.google.com/


# Ingrese su nombre corto de Disqus (no su nombre de usuario) para permitir comentar en publicaciones
# Puede encontrar su nombre corto en la página de Configuración de su cuenta de Disqus
disqus:

# Ingrese su código de seguimiento web de Google Analytics (por ejemplo, UA-2110908-2) para activar el seguimiento
google_analytics:

# URL de su sitio web (por ejemplo, http://barryclark.github.io o http://www.barryclark.co)
# Se utiliza para Sitemap.xml y su feed RSS
url: 

# Si está alojando su sitio en un repositorio de proyectos en páginas de GitHub
# http://yourusername.github.io/repository-name)
# y NO su repositorio de usuarios (http://yourusername.github.io)
# luego agregue la baseurl aquí, así: "/ nombre-repositorio"
baseurl: ""

#
# !! ¡No necesita cambiar ninguna de las opciones de configuración a continuación!
#

permalink: /:title/

# El lanzamiento de Jekyll Ahora que estás usando
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
